name: MLOps Major

on:
  push:
    branches: [main]

jobs:
  test_suite:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: generate the model
        run: python3 src/train.py

      - name: Run pytest
        run: pytest tests/

  train_and_quantize:
    name: Train and Quantize
    runs-on: ubuntu-latest
    needs: test_suite

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train model
        run: python src/train.py

      - name: Quantize model
        run: python src/quantize.py

  build_and_test_container:
    name: Docker Build & Predict
    runs-on: ubuntu-latest
    needs: train_and_quantize

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t mlops-app .

      - name: Run container and verify predictions
        run: docker run --rm mlops-app
